.TH wosp 1 wosp-0.0.0
.SH NAME
Wosp - advanced full-text search on the command line
.SH SYNOPSIS
.B wosp
.I QUERY
.RI [ FILE .\|.\|.]
.SH DESCRIPTION
Wosp is a command-line program that performs full-text search on text
documents.  Wosp stands for word-oriented search and print.  It is designed for
advanced searchers.  It works differently than line-oriented search tools like
grep, so it can search for matches spanning multiple lines.  Wosp supports an
expressive query language that contains both Boolean and proximity operators.
It also supports nested queries, trunctation, wildcard characters, and fuzzy
searching.
.SH COPYRIGHT
Copyright 2025 Andrew Trettel
.SH SEE ALSO
.BR grep (1)
.SH BUGS
Contact Andrew Trettel (https://www.andrewtrettel.com/) to report any bugs.
